<?php
    $this->load->view("header");
?>
<?php
    $this->load->view("$view");
?>
<?php
    $this->load->view("footer");
?>
<?php
    $this->load->view("script");
?>
<?php
    $this->load->view("style");
?>